FIX-UP: Relocate #define RENAME_NOREPLACE to fix compilation for A15.
out/soong/.intermediates/vendor/lineage/build/soong/generated_kernel_includes/gen/usr/include/linux/fs.h:39:9: error: 'RENAME_NOREPLACE' macro redefined [-Werror,-Wmacro-redefined]
   39 | #define RENAME_NOREPLACE        ( << )        /* Don't overwrite target */
      |         ^
bionic/libc/include/stdio.h:178:9: note: previous definition is here
  178 | #define RENAME_NOREPLACE (<<)
      |         ^
1 error generated.